ELASTICSEARCH_INDEX_NAME = 'gdmap_test'
MONGO_CACHE_NAME = 'cache_test'
MONGO_DATABASE_NAME = 'gdmap_test'
TEST_FIXTURES_DIR = 'gdmap/tests/fixtures'
DATA_DIRECTORY = '/gdmap/gdmap/tests/fixtures/data'
